### ISSUE TITLE
Can you post Pixel schematic ?

### ISSUE THREAD

**Issue by vziukas** [crossfireprod/Borealis#1]
Hi, great idea. 

I see schematic for DMX version. Can you post or explain how to connect in pixel mode? Will it work with ESPixelStick firmware ?

Thanks !

**Comment by crossfireprod** [comment]
@vziukas - Good catch, looking back it appears that I've posted schematic / PCB layout screenshots from an early version of the design.  I'll have to poke around a bit, but I expect to have updates committed by the end of the week.  In any case, yes, the ESPixelStick FW can be used for either DMX or "pixel" output.

**Comment by vziukas** [comment]
@crossfireprod thanks! Looking forward to see updated version.

**Comment by crossfireprod** [comment]
@vziukas - Updated (proper) design files have been committed.  Thanks again for the catch!  (After the initial design, @Ulto put together a DMX only version that I inadvertently included instead when initially creating this repository.)

Now that we've got the right design files, take a look at the schematic and you'll see the DATA_OUT/DMX- net is where the WS2812 pixels will get their data stream from.
https://raw.githubusercontent.com/crossfireprod/Borealis/master/Images/Schematic_Borealis_DMX%26Pixel.png

If you don't have any desire to make use of the DMX output functionality, feel free not to populate IC2, C2, and R1.

Hope this helps, let me us (@Ulto and I) know how you make out!
